# Generated by Django 3.0.8 on 2020-08-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='name')),
                ('description', models.CharField(blank=True, default='', max_length=1000, verbose_name='description')),
                ('parent', models.IntegerField(default=0, verbose_name='父节点')),
            ],
        ),
    ]
