# Generated by Django 3.0.8 on 2020-08-18 19:41

from django.db import migrations, models
import django.db.models.deletion
import star_app.models.base
import star_app.models.object_field


class Migration(migrations.Migration):

    dependencies = [
        ('star_app', '0002_interface'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(default='', max_length=500, verbose_name='description')),
                ('status', models.IntegerField(choices=[(0, '未执行'), (1, '执行中'), (2, '执行完成')], default=0, verbose_name='状态')),
            ],
            bases=(models.Model, star_app.models.base.Base),
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, verbose_name='创建时间')),
                ('version', models.CharField(default=1, max_length=10000, verbose_name='version')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='star_app.Task')),
            ],
            bases=(models.Model, star_app.models.base.Base),
        ),
        migrations.CreateModel(
            name='TaskInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='star_app.Interface')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='star_app.Task')),
            ],
            bases=(models.Model, star_app.models.base.Base),
        ),
        migrations.CreateModel(
            name='InterfaceResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(default='', max_length=500, verbose_name='description')),
                ('host', models.CharField(default='', max_length=200, verbose_name='host')),
                ('url', models.CharField(max_length=500, verbose_name='url')),
                ('method', models.CharField(max_length=20, verbose_name='method')),
                ('headers', star_app.models.object_field.ObjectField(default={}, verbose_name='headers')),
                ('parameter', star_app.models.object_field.ObjectField(default={}, verbose_name='parameter')),
                ('parameter_type', models.CharField(default='json', max_length=20, verbose_name='parameter_type,json or form')),
                ('response', star_app.models.object_field.ObjectField(default='', verbose_name='response')),
                ('response_type', models.CharField(default='json', max_length=20, verbose_name='parameter_type,json or form')),
                ('asserts', star_app.models.object_field.ObjectField(default=[], verbose_name='asserts')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('interface', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='star_app.Interface')),
                ('task_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='star_app.TaskResult')),
            ],
            bases=(models.Model, star_app.models.base.Base),
        ),
    ]
