# Generated by Django 3.0.8 on 2020-08-24 18:41

from django.db import migrations, models
import star_app.models.object_field


class Migration(migrations.Migration):

    dependencies = [
        ('star_app', '0003_interfaceresult_task_taskinterface_taskresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(default='', max_length=500, verbose_name='description')),
                ('method', models.CharField(default='get', max_length=20, verbose_name='method')),
                ('response_type', star_app.models.object_field.ObjectField(default={}, verbose_name='response')),
            ],
        ),
    ]
