# Generated by Django 3.0.8 on 2020-08-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('star_app', '0004_mock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mock',
            old_name='response_type',
            new_name='response',
        ),
    ]
